from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import mini_articraft
from pxr import Usd, UsdGeom

from .models import Artifact, CatalogItem, Joint, Limits, Origin, Part
from .storage import SupabaseStorage


async def generate_item(
    *,
    job_id: str,
    prompt: str,
    provider: str,
    model: str | None,
    image: Path | None,
    runs_dir: Path,
    storage: SupabaseStorage,
) -> CatalogItem:
    output_dir = runs_dir / job_id
    output_dir.mkdir(parents=True, exist_ok=True)
    result = await mini_articraft.generate_async(
        prompt,
        provider=provider,
        model=model,
        image=image,
        output_dir=output_dir,
    )
    if not result.succeeded or result.artifact is None:
        raise RuntimeError(
            result.error or result.message or "mini-articraft generation failed"
        )

    artifact_path = result.artifact.resolve()
    version = _viewer_version(result.run_dir, artifact_path)
    model_value = _dict(version.get("model"))
    storage_path = f"generated/{job_id}/model.usdz"
    artifact_url, digest = await storage.upload_artifact(storage_path, artifact_path)
    joints = _joints(model_value.get("articulations"))
    item = CatalogItem(
        id=f"generated:{job_id}",
        title=_title(prompt),
        description="Generated by mini-articraft through the Pascal Articraft worker.",
        artifact=Artifact(url=artifact_url, sha256=digest),
        dimensions=_dimensions(artifact_path),
        parts=_parts(model_value.get("parts")),
        joints=joints,
        defaultJointValues={
            joint.name: 0.0 for joint in joints if joint.type != "fixed"
        },
        prompt=prompt,
    )
    await storage.upload_manifest(
        f"generated/{job_id}/manifest.json",
        _public_manifest(item),
    )
    return item


def _public_manifest(item: CatalogItem) -> dict[str, object]:
    value = item.model_dump(mode="json")
    value.pop("prompt", None)
    return value


def _viewer_version(run_dir: Path, artifact: Path) -> dict[str, Any]:
    from mini_articraft.viewer import load_viewer_run

    viewer = load_viewer_run(run_dir)
    for version in viewer.versions:
        if version.get("filename") == artifact.name:
            return dict(version)
    if viewer.versions:
        return dict(viewer.versions[0])
    raise RuntimeError("mini-articraft returned an artifact without viewer metadata")


def _parts(value: object) -> list[Part]:
    if not isinstance(value, list):
        return []
    result: list[Part] = []
    for raw in value:
        part = _dict(raw)
        name = str(part.get("name", "")).strip()
        if name:
            result.append(Part(name=name, objectName=str(part.get("usd_name") or name)))
    return result


def _joints(value: object) -> list[Joint]:
    if not isinstance(value, list):
        return []
    result: list[Joint] = []
    for raw in value:
        joint = _dict(raw)
        joint_type = str(joint.get("type", "fixed"))
        if joint_type not in {"fixed", "revolute", "continuous", "prismatic"}:
            continue
        limits_value = _dict(joint.get("motion_limits"))
        limits = None
        if limits_value and joint_type not in {"fixed", "continuous"}:
            limits = Limits(
                lower=float(limits_value.get("lower", 0)),
                upper=float(limits_value.get("upper", 0)),
            )
        origin = _dict(joint.get("origin"))
        result.append(
            Joint(
                name=str(joint.get("name", "joint")),
                type=joint_type,
                parent=str(joint.get("parent", "")),
                child=str(joint.get("child", "")),
                axis=_vec3(joint.get("axis"), (0.0, 0.0, 1.0)),
                origin=Origin(
                    xyz=_vec3(origin.get("xyz"), (0.0, 0.0, 0.0)),
                    rpy=_vec3(origin.get("rpy"), (0.0, 0.0, 0.0)),
                ),
                limits=limits,
            )
        )
    return result


def _dimensions(path: Path) -> tuple[float, float, float]:
    stage = Usd.Stage.Open(str(path))
    if stage is None:
        return (1.0, 1.0, 1.0)
    cache = UsdGeom.BBoxCache(Usd.TimeCode.Default(), [UsdGeom.Tokens.default_])
    box = cache.ComputeWorldBound(stage.GetPseudoRoot()).ComputeAlignedRange()
    size = box.GetSize()
    return (
        max(float(size[0]), 0.01),
        max(float(size[1]), 0.01),
        max(float(size[2]), 0.01),
    )


def _vec3(
    value: object, fallback: tuple[float, float, float]
) -> tuple[float, float, float]:
    if not isinstance(value, (list, tuple)) or len(value) != 3:
        return fallback
    return (float(value[0]), float(value[1]), float(value[2]))


def _dict(value: object) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _title(prompt: str) -> str:
    words = re.sub(r"\s+", " ", prompt).strip().split(" ")
    return " ".join(words[:8]).capitalize()[:80] or "Generated Articraft object"
